### ISSUE TITLE
Incorrect Watson object names in documentation page

### ISSUE THREAD

**Issue by npo-rpa-solutions** [ibm-cloud-docs/watson-assistant#1]
In the documentation page https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-security, we found 2 incorrect server objects names.

The first one is from "[Authenticating users](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-security#web-chat-security-authenticate)" section: 

`The userID is stored in the context object as context.global.system.user_id.`

But global object is empty on the chatbot; we can only find the user_id as: **metadata.user_id**

The second one is from "[Passing sensitive data](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-security#web-chat-security-encrypt)" section:

`The encrypted user payload is decrypted and then saved to the context.integrations.chat.private.user_payload object.`

But we find the decoded payload in object: **integrations.chat.private.user_payload** (not inside context object)

Is it possible to check and update the page?
Thank you very much.

**Comment by amiddavid** [comment]
related to `user_payload` the prefix `context` is referencing the concept here https://cloud.ibm.com/apidocs/assistant/assistant-v2#message see `context` and as such is accurate.

related to `context.global.system.user_id` vs `metadata.user_id` I believe that if you are looking inside `metadata` it means you are using our `v1` - https://cloud.ibm.com/apidocs/assistant-v1#message
however our web chat is `v2` only per my first link above

**Comment by npo-rpa-solutions** [comment]
Hello @amiddavid , we are using the Web Chat integration script, embedded in a web page inside our application. The script is auto-generated, there is no option to choose the api version to be used. How can we check which api version are we really using?

**Comment by amiddavid** [comment]
the best way is to open the network tab and view the requests sent. If you do that, pls provide also the `x-request-id` header value so we can track the requests in the logs. 
could u provide which `region` is stated in your embedded code.

**Comment by npo-rpa-solutions** [comment]
Hello, the **region** in embedded code is "**eu-de**".

I attached a screenshot of network tab showing the requests. Where can I find the **x-request-id** header?

Thank you.

![WebChat_NetworkTab](https://user-images.githubusercontent.com/82641125/153209867-052a18cf-93d7-4248-a9f6-7c38369e1832.png)

**Comment by amiddavid** [comment]
if u scroll down in the `Response Headers` you will find it, but no on loading the widget. on an actual call to a message

The **Request URL** in the network tab should  be something like `https://integrations.eu-sw.assistant.watson.appdomain.cloud/<some-guid>/message/<some_other_guid>?version=2021-11-27`
