### ISSUE TITLE
Need to Have a Reference of Action Limits per Plan

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/watson-assistant#10]
The doc New watson Assistant needs to have doc on the number of Action Limits per plan
https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-build-actions-overview

Similar to the legacy doc https://cloud.ibm.com/docs/assistant?topic=assistant-intents#intents-limits

@rrberry @Peter Keller

**Comment by crlordan** [comment]
Published here:

**Comment by wksuser** [comment]
@crlordan where was this published? I don't see a link or anything

**Comment by crlordan** [comment]
Published here: https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-build-actions-overview#build-actions-limits
