### ISSUE TITLE
Please check duplication of words in your content

### ISSUE THREAD

**Issue by jrodolfo** [ibm-cloud-docs/watson-assistant#12]
The word "click" is duplicated in this sentence: "On the Integrations icon Integrations page, find the Web chat tile and click click Open. The Open web chat window opens."
Ref: https://cloud.ibm.com/docs/watson-assistant/watson-assistant?topic=watson-assistant-deploy-web-chat

**Comment by californiakat** [comment]
another page i read recently had the same error. ty for catching this.
