### ISSUE TITLE
Need to include Version Limits on Publishing

### ISSUE THREAD

**Issue by miltatibm** [ibm-cloud-docs/watson-assistant#2]
The doc about publishing should include version Limits
https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-publish

The graphics show 2 versions. But Lite Plans are only allowed one published version

**Comment by miltatibm** [comment]
@crlordan

**Comment by crlordan** [comment]
They are going to change the Lite plan so it can have 3 snapshots (versions): https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/53068

We are going to better highlight the plan limits in the topic. There's a marketing page that is the source of truth: https://www.ibm.com/products/watson-assistant/pricing

**Comment by Charlotte-Holt** [comment]
Update published in https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-publish
