### ISSUE TITLE
Incorrect link on https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-add-custom-extension

### ISSUE THREAD

**Issue by simon-lewis** [ibm-cloud-docs/watson-assistant#31]
Folks,
Was looking for instructions on _replacing_ an OpenAPI specification without destroying the extension. 
There is a link on this page (_docs/watson-assistant?topic=watson-assistant-add-custom-extension_) described as:

In the Manage extension step, you can review and replace the imported OpenAPI document if required. For more information about replacing the OpenAPI document, see [Replacing the OpenAPI document](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-add-custom-extension).

Note that the Link: **Replacing the OpenAPI document** merely points to the current page. Should it point elsewhere ?

Thanks
Simon

**Comment by californiakat** [comment]
thanks so much for pointing this out. i've corrected this to point to https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-build-custom-extension#replace-openapi-doc
