### ISSUE TITLE
Doc issue: Incorrect link on page https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-response-types-reference#response-types-json-user-defined

### ISSUE THREAD

**Issue by simon-lewis** [ibm-cloud-docs/watson-assistant#32]
Page: https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-response-types-reference#response-types-json-user-defined

Contains a link labelled "[Applying advanced customizations](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-config)."

Points to "https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-config"

Should point somewhere else, I think- there are several advanced configuration references.

Thanks.

**Comment by californiakat** [comment]
page has been updated
