### ISSUE TITLE
The link to api docs does not load 

### ISSUE THREAD

**Issue by jubinthomasibm** [ibm-cloud-docs/watson-assistant#46]
### Which topic are you reporting about?

Editing the disambiguation configuration
refer: https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-dialog-runtime#dialog-runtime-disambig-edit

### What do you think needs to be updated?

It should re-direct to the right document, or there shouldn't be the hyperlink. I could not find the right link for this  
![Screenshot 2024-10-15 at 10 02 10](https://github.com/user-attachments/assets/d1f6494f-1086-4661-a10f-c745b241cc52)

**Comment by californiakat** [comment]
the URL is correct https://cloud.ibm.com/apidocs/assistant-v1
however, my recollection is that this has been deprecated and removed.

i found: https://watson-developer-cloud.github.io/swift-sdk/services/AssistantV1/Classes/Assistant.html

**Comment by jubinthomasibm** [comment]
Watson assistant v1 is still available here : https://cloud.ibm.com/apidocs/assistant-v1
but the URL: https://cloud.ibm.com/assistant/assistant-v1?curl=#updateworkspace isn't accessible should be 
https://cloud.ibm.com/apidocs/assistant-v1#updateworkspace

**Comment by jubinthomasibm** [comment]
Hi @californiakat , I am able to access https://cloud.ibm.com/apidocs/assistant-v1#updateworkspace
<img width="1724" alt="Screenshot 2024-12-10 at 15 46 40" src="https://github.com/user-attachments/assets/0b5096c4-9bd1-4fde-bda4-da8f04f75ae8">

**Comment by californiakat** [comment]
that's great @jubinthomasibm but as i said above, not everyone can. so imo, that's not a solution

**Comment by californiakat** [comment]
it's https://cloud.ibm.com/apidocs/assistant-v1?code=node#updateworkspace

page has been updated.
