### ISSUE TITLE
Broken link on https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-webhook-post

### ISSUE THREAD

**Issue by andrewrfreed** [ibm-cloud-docs/watson-assistant#47]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-webhook-post

### What do you think needs to be updated?

https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-webhook-post
For a practical implementation of this feature, see [Example 3](https://cloud.ibm.com/#example-3) - link is broken, points to https://cloud.ibm.com/#example-3.  Should either be same page (example 1 or 2), or restore the deleted Example 3.

### Anything else?

> IBMers, don't use this repo to report issues. View the topic in the internal IBM Cloud docs staging site and open a doc issue from there.

If I had that link, I would do it.  Please share the link.

**Comment by californiakat** [comment]
example 3 is no longer mentioned on this page.

**Comment by californiakat** [comment]
also, as far as i know as the former tech writer for this product, logging an issue in this repo is fine :)
