### ISSUE TITLE
Bug: Watson Assistant Webhook Overview page doesn't reflect the current settings

### ISSUE THREAD

**Issue by thebiss** [ibm-cloud-docs/watson-assistant#6]
The page https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-webhook-overview states 
> You configure webhooks from the Settings>Webhooks page for the assistant.

On the v2 UI, Webhooks are set through the settings gear, on the environments page. See below
<img width="315" alt="image" src="https://user-images.githubusercontent.com/25112041/192591491-c1153f5a-5588-4366-ae05-1eedcc2c9b14.png">

**Comment by crlordan** [comment]
This was fixed.
