### ISSUE TITLE
Links are invalid

### ISSUE THREAD

**Issue by jigneshkvp** [ibm-cloud-docs/watson-assistant#7]
The following links under "More Information" section are invalid:

- For more information about billing, see [User-based plans explained](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-services-information#services-information-user-based-plans). _Returns Invalid_

- For more information about MAU limits per plan, see [Billing](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-overview#web-chat-architecture-billing). _The section is not found_

- For more information about deleting a user's data, see [Labeling and deleting data](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-information-security#information-security-gdpr-wa). _Returns Invalid_

The above links can be found here:
https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-web-chat-develop-userid

**Comment by californiakat** [comment]
thanks for the feedback. all three links have been fixed to reflect current location of info for each
